src/Entity/Comic.php
<?php

namespace App\Entity;

use App\Repository\ComicRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Event\PrePersistEventArgs;
use Doctrine\ORM\Event\PreUpdateEventArgs;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation as Serializer;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ComicRepository::class)]
#[ORM\Table(name: 'comic')]
#[ORM\HasLifecycleCallbacks]
#[ORM\Cache(usage: 'NONSTRICT_READ_WRITE')]
class Comic
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    #[ORM\Column(type: Types::BIGINT)]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE)]
    #[Serializer\Groups(['comic'])]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE, nullable: true)]
    #[Serializer\Groups(['comic'])]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column(length: 12, unique: true, options: ['collation' => 'utf8mb4_bin'])]
    #[Assert\NotBlank, Assert\Length(12)]
    #[Serializer\Groups(['comic'])]
    private ?string $code = null;

    /**
     * @var Collection<int, ComicDestinationLink>
     */
    #[ORM\OneToMany(targetEntity: ComicDestinationLink::class, mappedBy: 'comic', fetch: 'EXTRA_LAZY')]
    #[ORM\Cache(usage: 'NONSTRICT_READ_WRITE')]
    private Collection $destinationLinks;

    /**
     * @var Collection<int, ComicChapter>
     */
    #[ORM\OneToMany(targetEntity: ComicChapter::class, mappedBy: 'comic', fetch: 'EXTRA_LAZY')]
    #[ORM\Cache(usage: 'NONSTRICT_READ_WRITE')]
    private Collection $chapters;

    public function __construct()
    {
        $this->destinationLinks = new ArrayCollection();
        $this->chapters = new ArrayCollection();
    }

    #[ORM\PrePersist]
    public function onPrePersist(PrePersistEventArgs $args)
    {
        $this->setCreatedAt(new \DateTimeImmutable());
    }

    #[ORM\PreUpdate]
    public function onPreUpdate(PreUpdateEventArgs $args)
    {
        $this->setUpdatedAt(new \DateTimeImmutable());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): static
    {
        $this->code = $code;

        return $this;
    }

    /**
     * @return Collection<int, ComicDestinationLink>
     */
    public function getDestinationLinks(): Collection
    {
        return $this->destinationLinks;
    }

    #[Serializer\Groups(['comic'])]
    public function getDestinationLinkCount(): ?int
    {
        return $this->destinationLinks->count();
    }

    public function addDestinationLink(ComicDestinationLink $destinationLink): static
    {
        if (!$this->destinationLinks->contains($destinationLink)) {
            $this->destinationLinks->add($destinationLink);
            $destinationLink->setComic($this);
        }

        return $this;
    }

    public function removeDestinationLink(ComicDestinationLink $destinationLink): static
    {
        if ($this->destinationLinks->removeElement($destinationLink)) {
            // set the owning side to null (unless already changed)
            if ($destinationLink->getComic() === $this) {
                $destinationLink->setComic(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ComicChapter>
     */
    public function getChapters(): Collection
    {
        return $this->chapters;
    }

    #[Serializer\Groups(['comic'])]
    public function getChapterCount(): ?int
    {
        return $this->chapters->count();
    }

    public function addChapter(ComicChapter $chapter): static
    {
        if (!$this->chapters->contains($chapter)) {
            $this->chapters->add($chapter);
            $chapter->setComic($this);
        }

        return $this;
    }

    public function removeChapter(ComicChapter $chapter): static
    {
        if ($this->chapters->removeElement($chapter)) {
            // set the owning side to null (unless already changed)
            if ($chapter->getComic() === $this) {
                $chapter->setComic(null);
            }
        }

        return $this;
    }
}

src/Entity/Link.php
<?php

namespace App\Entity;

use App\Repository\LinkRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Event\PrePersistEventArgs;
use Doctrine\ORM\Event\PreUpdateEventArgs;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation as Serializer;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: LinkRepository::class)]
#[ORM\Table(name: 'link')]
#[ORM\UniqueConstraint(columns: ['website_id', 'relative_reference'])]
#[ORM\HasLifecycleCallbacks]
#[ORM\Cache(usage: 'NONSTRICT_READ_WRITE')]
class Link
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    #[ORM\Column(type: Types::BIGINT)]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE)]
    #[Serializer\Groups(['link'])]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE, nullable: true)]
    #[Serializer\Groups(['link'])]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'links')]
    #[ORM\JoinColumn(name: 'website_id', nullable: false, onDelete: 'CASCADE')]
    #[Assert\NotNull]
    private ?Website $website = null;

    #[ORM\Column(length: 255, options: ['default' => '', 'collation' => 'utf8mb4_bin'])]
    #[Assert\Length(min: 1, max: 255)]
    #[Assert\Regex('/^\/|\?|#/')]
    #[Serializer\Groups(['link'])]
    private ?string $relativeReference = null;

    /**
     * @var Collection<int, LinkItemLanguage>
     */
    #[ORM\OneToMany(targetEntity: LinkItemLanguage::class, mappedBy: 'link', fetch: 'EXTRA_LAZY')]
    #[ORM\Cache(usage: 'NONSTRICT_READ_WRITE')]
    private Collection $itemLanguages;

    public function __construct()
    {
        $this->itemLanguages = new ArrayCollection();
    }

    #[ORM\PrePersist]
    public function onPrePersist(PrePersistEventArgs $args)
    {
        $this->setCreatedAt(new \DateTimeImmutable());

        if ($this->relativeReference == null) $this->setRelativeReference('');
    }

    #[ORM\PreUpdate]
    public function onPreUpdate(PreUpdateEventArgs $args)
    {
        $this->setUpdatedAt(new \DateTimeImmutable());

        if ($this->relativeReference == null) $this->setRelativeReference('');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getWebsite(): ?Website
    {
        return $this->website;
    }

    #[Serializer\Groups(['link'])]
    public function getWebsiteHost(): ?string
    {
        if ($this->website == null) {
            return null;
        }

        return $this->website->getHost();
    }

    #[Serializer\Groups(['link'])]
    public function getWebsiteName(): ?string
    {
        if ($this->website == null) {
            return null;
        }

        return $this->website->getName();
    }

    public function setWebsite(?Website $website): static
    {
        $this->website = $website;

        return $this;
    }

    public function getRelativeReference(): ?string
    {
        if ($this->relativeReference == '') {
            return null;
        }

        return $this->relativeReference;
    }

    public function setRelativeReference(?string $relativeReference): static
    {
        $this->relativeReference = $relativeReference;

        return $this;
    }

    /**
     * @return Collection<int, LinkItemLanguage>
     */
    public function getItemLanguages(): Collection
    {
        return $this->itemLanguages;
    }

    #[Serializer\Groups(['link'])]
    public function getItemLanguageCount(): ?int
    {
        return $this->itemLanguages->count();
    }

    public function addItemLanguage(LinkItemLanguage $itemLanguage): static
    {
        if (!$this->itemLanguages->contains($itemLanguage)) {
            $this->itemLanguages->add($itemLanguage);
            $itemLanguage->setLink($this);
        }

        return $this;
    }

    public function removeItemLanguage(LinkItemLanguage $itemLanguage): static
    {
        if ($this->itemLanguages->removeElement($itemLanguage)) {
            // set the owning side to null (unless already changed)
            if ($itemLanguage->getLink() === $this) {
                $itemLanguage->setLink(null);
            }
        }

        return $this;
    }
}

src/Entity/LinkItemLanguage.php
<?php

namespace App\Entity;

use App\Repository\LinkItemLanguageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Event\PrePersistEventArgs;
use Doctrine\ORM\Event\PreUpdateEventArgs;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation as Serializer;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: LinkItemLanguageRepository::class)]
#[ORM\Table(name: 'link_item_language')]
#[ORM\UniqueConstraint(columns: ['link_id', 'language_id'])]
#[ORM\HasLifecycleCallbacks]
#[ORM\Cache(usage: 'NONSTRICT_READ_WRITE')]
class LinkItemLanguage
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    #[ORM\Column(type: Types::BIGINT)]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE)]
    #[Serializer\Groups(['link', 'linkItemLanguage'])]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE, nullable: true)]
    #[Serializer\Groups(['link', 'linkItemLanguage'])]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'itemLanguages')]
    #[ORM\JoinColumn(name: 'link_id', nullable: false, onDelete: 'CASCADE')]
    #[Assert\NotNull]
    private ?Link $link = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name: 'language_id', nullable: false, onDelete: 'CASCADE')]
    #[Assert\NotNull]
    private ?Language $language = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    #[Assert\Range(min: -1, max: 1)]
    #[Serializer\Groups(['link', 'linkItemLanguage'])]
    private ?int $machineTranslate = null;

    #[ORM\PrePersist]
    public function onPrePersist(PrePersistEventArgs $args)
    {
        $this->setCreatedAt(new \DateTimeImmutable());
    }

    #[ORM\PreUpdate]
    public function onPreUpdate(PreUpdateEventArgs $args)
    {
        $this->setUpdatedAt(new \DateTimeImmutable());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getLink(): ?Link
    {
        return $this->link;
    }

    #[Serializer\Groups(['linkItemLanguage'])]
    public function getLinkWebsiteHost(): ?string
    {
        if ($this->link == null) {
            return null;
        }

        return $this->link->getWebsiteHost();
    }

    #[Serializer\Groups(['linkItemLanguage'])]
    public function getLinkRelativeReference(): ?string
    {
        if ($this->link == null) {
            return null;
        }

        return $this->link->getRelativeReference();
    }

    public function setLink(?Link $link): static
    {
        $this->link = $link;

        return $this;
    }

    public function getLanguage(): ?Language
    {
        return $this->language;
    }

    #[Serializer\Groups(['link', 'linkItemLanguage'])]
    public function getLanguageLang(): ?string
    {
        if ($this->language == null) {
            return null;
        }

        return $this->language->getLang();
    }

    public function setLanguage(?Language $language): static
    {
        $this->language = $language;

        return $this;
    }

    public function getMachineTranslate(): ?int
    {
        return $this->machineTranslate;
    }

    public function setMachineTranslate(?int $machineTranslate): static
    {
        $this->machineTranslate = $machineTranslate;

        return $this;
    }
}

src/Controller/ComicController.php
<?php

namespace App\Controller;

use App\Model\OrderByDto;
use App\Repository\ComicRepository;
use App\Service\ComicBagiApp;
use App\Service\ComicKingApi;
use App\Util\UrlQuery;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute as HttpKernel;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Attribute as Routing;

#[Routing\Route('/comics', name: 'app_comic_')]
class ComicController extends AbstractController
{
    public function __construct(
        private readonly ComicRepository $comicRepository,
        private readonly ComicBagiApp $comicBagiApp,
        private readonly ComicKingApi $comicKingApi
    ) {}

    #[Routing\Route('/', name: 'index')]
    #[HttpKernel\Cache(public: true, maxage: 1800, mustRevalidate: true)]
    public function index(
        Request $request,
        #[HttpKernel\MapQueryParameter(options: ['min_range' => 1])] int $page = 1,
        #[HttpKernel\MapQueryParameter(options: ['min_range' => 1, 'max_range' => 15])] int $limit = 10,
        #[HttpKernel\MapQueryParameter] string $type = ''
    ): Response {
        $queryString = $request->server->get('QUERY_STRING');
        $queries = new UrlQuery($queryString);

        return $this->render('comic/index.html.twig', [
            'rawParameter' => $queryString,
            'paramPage' => $page,
            'paramLimit' => $limit,
            'paramOrderBy' => $queries->all('orderBy'),
            'paramType' => $type,
            'resultCount' => $this->comicRepository->countCustom([])
        ]);
    }

    #[Routing\Route('/{code}', name: 'individual')]
    #[HttpKernel\Cache(public: true, maxage: 3600, mustRevalidate: true)]
    public function individual(
        Request $request,
        string $code,
        #[HttpKernel\MapQueryParameter(options: ['min_range' => 1])] int $chapterPage = 1
    ): Response {
        $queryString = $request->server->get('QUERY_STRING');

        $result = $this->comicRepository->findOneBy(['code' => $code]);
        if (!$result) throw new NotFoundHttpException('Comic not found.');

        return $this->render('comic/individual.html.twig', [
            'rawParameter' => $queryString,
            'paramCode' => $code,
            'paramChapterPage' => $chapterPage,
            'result' => $result,
            'funcComicBagiApp' => $this->comicBagiApp,
            'funcComicKingApi' => $this->comicKingApi
        ]);
    }

    #[HttpKernel\Cache(public: true, maxage: 900, mustRevalidate: true)]
    public function fragmentList(
        int $limit,
        int $page,
        array $orderBy = null,
        string $type = null
    ): Response {
        $result = $this->comicRepository->findByCustom(
            [],
            \array_map([OrderByDto::class, 'parse'], $orderBy),
            $limit,
            $limit * ($page - 1)
        );

        return $this->render('comic/_list.html.twig', [
            'paramLimit' => $limit,
            'paramPage' => $page,
            'paramOrderBy' => $orderBy,
            'paramType' => $type,
            'result' => $result,
            'funcComicBagiApp' => $this->comicBagiApp,
            'funcComicKingApi' => $this->comicKingApi
        ]);
    }

    #[HttpKernel\Cache(public: true, maxage: 900, mustRevalidate: true)]
    public function fragmentWidget(
        int $limit,
        array $orderBy = null
    ): Response {
        $result = $this->comicRepository->findByCustom(
            [],
            \array_map([OrderByDto::class, 'parse'], $orderBy),
            $limit,
            null
        );

        return $this->render('comic/_widget.html.twig', [
            'paramLimit' => $limit,
            'paramOrderBy' => $orderBy,
            'result' => $result,
            'funcComicBagiApp' => $this->comicBagiApp,
            'funcComicKingApi' => $this->comicKingApi
        ]);
    }
}

templates/comic/_individual__links.html.twig
{% set ordered_links = {} %}

{% set links_matches = [] %}
{% for language in dis_langs|merge(['🤔']) %}
    {% set language_links = [] %}

    {% for i, link in links %}
        {% set link_match = false %}

        {% set link_item_languages = funcComicBagiApp.linkItemLanguages(link.websiteHost, link.relativeReference) %}
        {% for link_item_language in link_item_languages %}
            {% if link_item_language.languageLang starts with language %}
                {% set link_match = true %}
            {% endif %}
        {% endfor %}

        {% if not link_match and not link_item_languages %}
            {% set link_website = link.website %}

            {% for website_item_language in funcComicBagiApp.websiteItemLanguages(link_website.host) %}
                {% if website_item_language.languageLang starts with language %}
                    {% set link_match = true %}
                {% endif %}
            {% endfor %}
        {% endif %}

        {% if not link_match and language == '🤔' and i not in links_matches %}
            {% set link_match = true %}
        {% endif %}

        {% if link_match %}
            {% set language_links = language_links|merge([link]) %}
            {% set links_matches = links_matches|merge([i]) %}
        {% endif %}
    {% endfor %}

    {% if language_links|length > 0 %}
        {% set ordered_links = ordered_links|merge({(language): language_links}) %}
    {% endif %}
{% endfor %}

{% for lang, links in ordered_links %}
    <div id="{{ links_id ?? '' }}" class="{{ links_class ?? '' }}">
        <span class="d-block w-100 text-center p-2">--- {{ lang|upper }} ---</span>
        <div class="row row-cols-1 {{ links|length > 1 ? 'row-cols-sm-2' : '' }} g-1 m-0">
            {% for link in links %}
                <div class="col">
                    <a
                        target="_blank"
                        href="{{ funcComicBagiApp.href(link.websiteHost, link.relativeReference) }}"
                        rel="noreferrer nofollow"
                        class="d-block text-truncate text-decoration-none p-2 border"
                    ><img
                        src="{{ funcComicBagiApp.href(link.websiteHost, '/favicon.ico') }}"
                        alt=""
                        style="height: 24px; width: 24px;"
                    /> {{ link.websiteName }}</a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endfor %}

templates/comic/_individual_chapters.html.twig
<div class="p-3 border border-2">
    <h2 class="text-center fs-6 pb-2 border-bottom">CHAPTERS</h2>

    {% if result.chapterCount > 0 %}
        {% set comic_chapters = funcComicBagiApp.comicChapters(result.code, comic_chapter_limit, comic_chapter_offset) %}
        <div class="d-flex flex-column gap-2">
            <div class="row row-cols-1 {{ comic_chapters|length > 1 ? 'row-cols-sm-2' : '' }} g-1 m-0">
                {% for chapter in comic_chapters %}
                    <div class="col">
                        <div class="border">
                            {% set links = funcComicBagiApp.linksByComicChapter(
                                result.code,
                                chapter.number,
                                chapter.version,
                                rec_langs
                            ) %}

                            <button
                                class="w-100 btn text-start {{ links|length < 1 ? 'text-secondary' : '' }} p-2"
                                data-bs-toggle="collapse"
                                data-bs-target="#chapterLinks-{{ loop.index }}"
                            >{{
                                'Chapter ' ~ chapter.number
                                ~ (chapter.version ? ' (' ~ chapter.version ~ ')' : '')
                            }}</button>

                            {% if links|length > 0 %}
                                {% set links_id = 'chapterLinks-' ~ loop.index %}
                                {% set links_class = 'collapse p-2' %}
                                {{ include('comic/_individual__links.html.twig') }}
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>

            <nav class ="">
                <ul class="pagination justify-content-center m-0">
                    {% set rawParameter = rawParameter|replace({
                        ('chapterPage=' ~ paramChapterPage): '',
                        ('chapterPage=' ~ paramChapterPage ~ '&'): '',
                        ('&chapterPage=' ~ paramChapterPage): ''
                    }) %}

                    {% set prevPageNum = paramChapterPage - 1 %}
                    {% set prevPageRef = path('app_comic_individual', { code: result.code, chapterPage: prevPageNum }) %}
                    {% if rawParameter %}
                        {% set prevPageRef = prevPageRef ~ '&' ~ rawParameter %}
                    {% endif %}
                    {% set prevPageTes = paramChapterPage > 1 %}
                    <li class="page-item{{ prevPageTes ? '' : ' disabled' }}">
                        <a class="page-link" href="{{ prevPageRef }}">Prev</a>
                    </li>

                    <li class="page-item active">
                        <span class="page-link">{{ paramChapterPage }}</span>
                    </li>

                    {% set nextPageNum = paramChapterPage + 1 %}
                    {% set nextPageRef = path('app_comic_individual', { code: result.code, chapterPage: nextPageNum }) %}
                    {% if rawParameter %}
                        {% set nextPageRef = nextPageRef ~ '&' ~ rawParameter %}
                    {% endif %}
                    {% set nextPageTes = result.chapterCount > comic_chapter_limit * paramChapterPage %}
                    <li class="page-item{{ nextPageTes ? '' : ' disabled' }}">
                        <a class="page-link" href="{{ nextPageRef }}">Next</a>
                    </li>
                </ul>
            </nav>
        </div>
    {% else %}
        {{ include('_err.html.twig', { message: 'No Chapter Found' }) }}
    {% endif %}
</div>

templates/comic/_individual_websites.html.twig
<div class="p-3 border border-2">
    <h2 class="text-center fs-6 pb-2 border-bottom">WEBSITES</h2>

    {% set links = funcComicBagiApp.linksByComic(result.code, rec_langs) %}
    {% if links|length > 0 %}
        {{ include('comic/_individual__links.html.twig') }}
    {% else %}
        {{ include('_err.html.twig', { message: 'No Link Found' }) }}
    {% endif %}
</div>

templates/comic/_list.html.twig
{% if result %}
    {% set req_langs = app.request.languages|map(l => l|replace({'_': '-'})) %}
    {% set app_langs = funcComicBagiApp.languages(null)|map(l => l.lang) %}
    {% set rec_langs = funcComicBagiApp.recommendedLangs(app_langs, req_langs) %}

    <style>
        @media (max-width: 415.98px) {
            .list-card {
                --comic-card-h: 192px;
                --comic-card-cover-w: 144px;
                --comic-card-synopsis-h: 124px;
            }
        }
    </style>

    {% if paramType == 'b' %}
        {% set listWrapperClass = 'row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-6' %}
        {% set listCardIncludePath = 'comic/_listb_card.html.twig' %}
    {% else %}
        {% set listWrapperClass = 'row-cols-1 row-cols-lg-2' %}
        {% set listCardIncludePath = 'comic/_lista_card.html.twig' %}
    {% endif %}

    <div class="row {{ listWrapperClass }} g-3">
        {% for comic in result %}
            <div class="col list-card">
                {{ include(listCardIncludePath) }}
            </div>
        {% endfor %}
    </div>
{% else %}
    {{ include('_err.html.twig', { message: 'No Comic Found' }) }}
{% endif %}

templates/comic/_lista_card.html.twig
<div class="row m-0 shadow">
    {% set comic_href = path('app_comic_individual', { code: comic.code }) %}
    {% set comic_titles = funcComicKingApi.comicTitles(comic.code, rec_langs, 1) %}
    {% if comic_titles|length > 0 %}
        {% set comic_title = comic_titles[0] %}
    {% endif %}

    <a
        href="{{ comic_href }}"
        class="col p-0 bg-dark"
        style="height: var(--comic-card-h); max-width: var(--comic-card-cover-w);"
    >
        {% set comic_covers = funcComicKingApi.comicCovers(comic.code, [], 1) %}
        {% if comic_covers|length > 0 %}
            {% set comic_cover = comic_covers[0] %}
        {% else %}
            {% set comic_cover = null %}
        {% endif %}
        <img
            src="{{
                comic_cover
                ? funcComicBagiApp.href(comic_cover.linkWebsiteHost, comic_cover.linkRelativeReference)
                : asset('images/comic-cover.jpg')
            }}"
            alt="{{ comic_title.content ?? 'Comic' }} Cover"
            class="w-100 h-100 object-fit-cover"
        >
    </a>

    <div class="col overflow-hidden p-3" style="height: var(--comic-card-h);">
        <a href="{{ comic_href }}" class="text-decoration-none">
            <h5 class="text-truncate pb-2 border-bottom">{{ comic_title.content ?? 'No Title' }}</h5>
        </a>
        <div class="comic-card-synopsis overflow-y-auto" style="height: var(--comic-card-synopsis-h);">
            {% set comic_synopses = funcComicKingApi.comicSynopses(comic.code, [], rec_langs, 1) %}
            {% if comic_synopses|length > 0 %}
                {% set comic_synopsis = comic_synopses[0] %}
            {% endif %}
            {% if comic_synopsis.content ?? false %}
                {{ comic_synopsis.content|markdown_to_html }}
            {% else %}
                {{ 'Empty synopsis.' }}
            {% endif %}
        </div>
    </div>
</div>

templates/comic/_style.html.twig
<style>
    :root {
        --comic-card-h: 256px;
        --comic-card-cover-w: 192px;
        --comic-card-synopsis-h: 188px;
    }

    .comic-card-synopsis {
        scrollbar-width: thin;
    }

    @media (min-width: 768px) {
        .comic-card {
            height: var(--comic-card-h);
        }

        .comic-card-synopsis {
            height: var(--comic-card-synopsis-h);
        }
    }
</style>